version: '3'

services:

  mariadb:
    build:
      context: ./mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - MARIADB_VERSION=${MARIADB_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - backend

  nginx:
    image: nginx
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_SERVICE=fpm
        - PHP_UPSTREAM_PORT=9000
    volumes:
      - ${LOCAL_SOURCE_PATH}:/var/www
      - ${NGINX_LOG_PATH}:/var/log/nginx
    environment:
      - BACKEND=fpm
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - fpm

  fpm:
    image: php-fpm
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - INSTALL_XDEBUG=false
        - INSTALL_OPCACHE=false
        - INSTALL_AMQP=false
        - INSTALL_SOAP=true
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
    volumes:
      - ${LOCAL_SOURCE_PATH}:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/pool.conf:/usr/local/etc/php-fpm.d/pool.conf
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    expose:
      - "9000"
    restart: unless-stopped
    depends_on:
      - mariadb
    links:
      - mariadb
    networks:
      - backend


networks:
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  mariadb:
    driver: ${VOLUMES_DRIVER}
